# Generated by Django 6.0.1 on 2026-02-02 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_moodentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session'], name='chat_chatme_session_cfafa5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='chat_chatme_timesta_f0eb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user'], name='chat_mooden_user_id_aeeab4_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['created_at'], name='chat_mooden_created_f5dff2_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['user'], name='chat_therap_user_id_a00532_idx'),
        ),
        migrations.AddIndex(
            model_name='therapysession',
            index=models.Index(fields=['created_at'], name='chat_therap_created_606627_idx'),
        ),
    ]
